### ISSUE TITLE
Constants for COMMAND and RESPONSE_AUTH are the same

### ISSUE THREAD

**Issue by electricessence** [levrik/node-modern-rcon#1]
This simply seems problematic to me.  Can you explain?

**Comment by levrik** [comment]
It's defined like that in the spec.
See https://developer.valvesoftware.com/wiki/Source_RCON_Protocol#Requests_and_Responses and http://wiki.vg/RCON#3:_Login

**Comment by electricessence** [comment]
Ok got it.  It's the same for different operations.
Just finished this:
https://github.com/electricessence/rcon-ts (fork of your repo)

**Comment by levrik** [comment]
@electricessence Why didn't you contribute typings to this repo? Just curious 🙂

**Comment by electricessence** [comment]
I'm all for starting a pull request, but I've gone beyond just adding a *.d.ts.
Once you switch to TS, certain patterns show up.  The *.js and *.d.ts files are in NPM.

**Comment by electricessence** [comment]
I'm still working out the kinks too.   Remember to include them in your package.json as "typings":"[name].d.ts".
[rcon.d.ts.zip](https://github.com/levrik/node-modern-rcon/files/1936047/rcon.d.ts.zip)

Here's the current d.ts file as it's being rendered.  It's going to be different than yours but might be useful with a few tweaks.
